import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>La verdad sobre Miccol</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenido a la verdad sobre <a href="https://nextjs.org">Miccol!</a>
        </h1>

        <p className={styles.description}>
          Indice de Archivos{' '}
        </p>

        <div className={styles.grid}>
          <a href="../" className={styles.card}>
            <h2>Fotos de Miccol &rarr;</h2>
            <p>Expandir archivo de fotos de Miccol</p>
          </a>

          <a href="../" className={styles.card}>
            <h2>Fotos de Mateo &rarr;</h2>
            <p>Expandir archivo de fotos de Mateo</p>
          </a>

          <a href="../" className={styles.card}>
            <h2>Fotos de Matrix &rarr;</h2>
            <p>Expandir archivo de fotos de Matrix</p>
          </a>

          <a href="../" className={styles.card}>
            <h2>Fotos de Quimera &rarr;</h2>
            <p>Expandir archivo de fotos de Quimera</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
      <a href="https://info.flagcounter.com/lvj6"><img src="https://s11.flagcounter.com/count2/lvj6/bg_FFFFFF/txt_000000/border_CCCCCC/columns_2/maxflags_10/viewers_0/labels_0/pageviews_0/flags_0/percent_0/" alt="Flag Counter" border="0"/></a>
      <a href="https://www.flagcounter.me/details/cjY"><img src="https://www.flagcounter.me/cjY/" alt="Flag Counter"/></a>
      </footer>
    </div>
  )
}
